# Site settings
title: OKR Guide
description: > # this means to ignore newlines until "baseurl:"
  A guide to Google and Doerr's OKRs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.theokrguide.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
